Repository adeeb27/ecse428-potatopeeps, pull requests merged in 2019-03, with the labels that each got.

#9 Edit menu item
  src/main/java/ca/mcgill/ecse428/potatopeeps/config/DatabaseLoader.java
  src/main/js/app.js
  src/main/resources/application.properties
Labels: bug, help wanted

#17 Request to Merge Manager
  package.json
  src/main/js/components/App.js
  src/main/js/components/Customer.js
  src/main/js/components/Login.js
  src/main/js/components/Manager.js
  src/main/js/components/subcomponents/MenuItem.js
  src/main/resources/static/css/Customer.css
  src/main/resources/static/css/customer.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/select-task.css
  src/main/resources/static/css/select_table_num.css
  src/main/resources/static/css/staff.css
  src/main/resources/templates/index.html
Labels: help wanted

#22 Css fix, customer items, select task page
  .gitignore
  src/main/js/components/Login.js
  src/main/js/components/Manager.js
  src/main/js/components/subcomponents/MenuItem.js
  src/main/resources/static/css/customer.css
  src/main/resources/static/css/login.css
Labels: wontfix
